name: pikaday_datepicker_angular2
description: Provides a datepicker as AngularDart3 component which wrapps the lightweight pikaday js-library.
version: 2.2.0
author: Stephan Schroeder <simon.void+github@gmail.com>
homepage: https://github.com/simon-void/pikaday_datepicker_angular2
environment:
  sdk: '>=1.23.0 <1.25.0'
dependencies:
  angular2: ^3.0.0
  js: ^0.6.1
  pikaday:
    git:
      url: https://github.com/simon-void/pikaday-dart.git
      ref: master
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
### (default) configuration if this package should be used as a library (import) or if the app should be execute as Dart in Dartium
- angular2
### configuration if example web folder should be compiled to js
#- angular2:
#    platform_directives:
#    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
#    platform_pipes:
#    - 'package:angular2/common.dart#COMMON_PIPES'
#    entry_points: web/main.dart
- dart_to_js_script_rewriter