name: pikaday_datepicker_angular2
description: Provides a datepicker as AngularDart3 component which wrapps the lightweight pikaday js-library.
version: 2.2.0
author: Stephan Schroeder <simon.void+github@gmail.com>
homepage: https://github.com/simon-void/pikaday_datepicker_angular2
environment:
  sdk: '>=1.23.0 <1.25.0'
dependencies:
  angular2: 3.1.0
  js: ^0.6.1
  pikaday:
    git:
      url: https://github.com/simon-void/pikaday-dart.git
      ref: 1.2.0
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2
